package com.PlanetCore.blocks;

public enum PlanetHardness {
    PAINITE_SUPERCOMPACT(2380),
    ONYX_SUPERCOMPACT(2000),
    AMAZONITE_SUPERCOMPACT(1800),
    MAJORITE_SUPERCOMPACT(1600),
    SAPPHIRE_SUPERCOMPACT(500),
    RUBY_SUPERCOMPACT(400),
    TUNGSTEN_SUPERCOMPACT(180),
    URANIUM_SUPERCOMPACT(70),
    TITANIUM_SUPERCOMPACT(70),
    EMERALD_SUPERCOMPACT(50.0F),
    DIAMOND_SUPERCOMPACT(50.0F),
    GOLD_SUPERCOMPACT(22.0F),
    SILVER_SUPERCOMPACT(19.0F),
    IRON_SUPERCOMPACT(13.5F),
    LAPIS_SUPERCOMPACT(8.5F),
    REDSTONE_SUPERCOMPACT(8.5F),
    SULFUR_SUPERCOMPACT(7.5F),
    COAL_SUPERCOMPACT(6.5F),

    PAINITE_COMPACT(2000),
    ONYX_COMPACT(1500),
    AMAZONITE_COMPACT(1300),
    MAJORITE_COMPACT(1000),
    SAPPHIRE_COMPACT(250),
    RUBY_COMPACT(200),
    TUNGSTEN_COMPACT(70),
    URANIUM_COMPACT(22),
    TITANIUM_COMPACT(22),
    EMERALD_COMPACT(19.0F),
    DIAMOND_COMPACT(19.0F),
    GOLD_COMPACT(15.0F),
    SILVER_COMPACT(13.4F),
    IRON_COMPACT(8.5F),
    LAPIS_COMPACT(6.5F),
    REDSTONE_COMPACT(6.5F),
    SULFUR_COMPACT(5.5F),
    COAL_COMPACT(4.5F),

    PAINITE(990),
    PAINITE_SMALL(860),
    ONYX(760),
    ONYX_SMALL(650),
    AMAZONITE(550),
    MAJORITE(450),
    SAPPHIRE(90),
    RUBY(65),
    TUNGSTEN(20),
    URANIUM(10),
    TITANIUM(10),
    EMERALD(8.5F),
    DIAMOND(7.0F),
    GOLD(6.0F),
    SILVER(5.0F),
    IRON(3.5F),
    LAPIS(3),
    REDSTONE(3),
    SULFUR(2),
    COAL(0.5F);

    public final float hardness;

    PlanetHardness(float hardness) {
        this.hardness = hardness;
    }
}