package com.PlanetCore.cwg.cell;

import static com.PlanetCore.cwg.cell.CellCaveType.builder;

public class CellCaveTypes {

    public static final CellCaveType NO_CAVE = builder()
            .cellWallTransitionHardness(0)
            .scaleFactor(0)
            .caveScale(0)
            .placementScale(0)
            .caveSystemSizeFactor(0)
            .transitionConstant1(0)
            .transitionConstant2(0)
            .caveOctaves(0)
            .placementOctaves(0)
            .caveFillConstant(0)
            .yCutoffMax(Double.POSITIVE_INFINITY)
            .yCutoffFactorCaveMax(0)
            .yCutoffFactorPlacementMax(0)
            .yCutoffMin(Double.NEGATIVE_INFINITY)
            .yCutoffFactorCaveMin(0)
            .yCutoffFactorPlacementMin(0)
            .build();

    public static final CellCaveType DEFAULT_1 = builder()
            .cellWallTransitionHardness(2)
            .scaleFactor(2)
            .caveScale(1 / 50.0)
            .placementScale(1 / 1024.0)
            .caveSystemSizeFactor(0.30)
            .transitionConstant1(40)
            .transitionConstant2(0.10)
            .caveOctaves(8)
            .placementOctaves(8)
            .caveFillConstant(0.0)
            .yCutoffMax(Double.POSITIVE_INFINITY)
            .yCutoffFactorCaveMax(0)
            .yCutoffFactorPlacementMax(0)
            .yCutoffMin(Double.NEGATIVE_INFINITY)
            .yCutoffFactorCaveMin(0)
            .yCutoffFactorPlacementMin(0)
            .build();
    public static final CellCaveType DEFAULT_2 = builder()
            .cellWallTransitionHardness(2)
            .scaleFactor(2)
            .caveScale(1 / 50.0)
            .placementScale(1 / 1024.0)
            .caveSystemSizeFactor(0.27)
            .transitionConstant1(40)
            .transitionConstant2(0.11)
            .caveOctaves(16)
            .placementOctaves(16)
            .caveFillConstant(0.0)
            .yCutoffMax(-32)
            .yCutoffFactorCaveMax(0.004)
            .yCutoffFactorPlacementMax(0.004)
            .yCutoffMin(-1500)
            .yCutoffFactorCaveMin(-0.000000000001)
            .yCutoffFactorPlacementMin(-0.000000000001)
            .build();

    public static final CellCaveType DEFAULT_3 = builder()
            .cellWallTransitionHardness(2)
            .scaleFactor(1)
            .caveScale(0.01)
            .placementScale(3 / 512.0)
            .caveSystemSizeFactor(0)
            .transitionConstant1(40)
            .transitionConstant2(0.26)
            .caveOctaves(16)
            .placementOctaves(16)
            .caveFillConstant(0.0)
            .yCutoffMax(-32)
            .yCutoffFactorCaveMax(0.004)
            .yCutoffFactorPlacementMax(0.004)
            .yCutoffMin(-1500)
            .yCutoffFactorCaveMin(-0.001)
            .yCutoffFactorPlacementMin(-0.001)
            .build();
    public static final CellCaveType DEFAULT_4 = builder()
            .cellWallTransitionHardness(2)
            .scaleFactor(2)
            .caveScale(1 / 50.0)
            .placementScale(1 / 1024.0)
            .caveSystemSizeFactor(0.27)
            .transitionConstant1(40)
            .transitionConstant2(0.4)
            .caveOctaves(8)
            .placementOctaves(8)
            .caveFillConstant(0.0)
            .yCutoffMax(-1500)
            .yCutoffFactorCaveMax(0.004)
            .yCutoffFactorPlacementMax(0.004)
            .yCutoffMin(-2200)
            .yCutoffFactorCaveMin(0.001)
            .yCutoffFactorPlacementMin(0.001)
            .build();

    public static final CellCaveType EXAMPLE = builder()
            .cellWallTransitionHardness(5)
            .scaleFactor(2)
            .caveScale(1 / 50.0)
            .placementScale(1)
            .caveSystemSizeFactor(0.27)
            .transitionConstant1(40)
            .transitionConstant2(0.4)
            .caveOctaves(8)
            .placementOctaves(0)
            .caveFillConstant(0.2)
            .yCutoffMax(Double.POSITIVE_INFINITY)
            .yCutoffFactorCaveMax(0)
            .yCutoffFactorPlacementMax(0)
            .yCutoffMin(Double.NEGATIVE_INFINITY)
            .yCutoffFactorCaveMin(0)
            .yCutoffFactorPlacementMin(0)
            .build();

    public static final CellCaveType EXAMPLE_2 = builder()
            .cellWallTransitionHardness(2)
            .scaleFactor(2)
            .caveScale(1 / 70.0)
            .placementScale(1)
            .caveSystemSizeFactor(0.27)
            .transitionConstant1(40)
            .transitionConstant2(0.4)
            .caveOctaves(2)
            .placementOctaves(0)
            .caveFillConstant(0.25)
            .yCutoffMax(Double.POSITIVE_INFINITY)
            .yCutoffFactorCaveMax(0)
            .yCutoffFactorPlacementMax(0)
            .yCutoffMin(Double.NEGATIVE_INFINITY)
            .yCutoffFactorCaveMin(0)
            .yCutoffFactorPlacementMin(0)
            .build();

}
